[package]
name = "ryo3-zstd"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "python + zstd (https://docs.rs/zstd/latest/zstd/)"

[dependencies]
pyo3 = { workspace = true, features = [] }
ryo3-bytes.workspace = true
zstd.workspace = true
zstd-safe.workspace = true

[lints]
workspace = true
