[package]
name = "ryo3-size"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "python + size crate (https://crates.io/crates/size)"

[dependencies]
pyo3 = { workspace = true, features = [] }
ryo3-core.workspace = true
size = { workspace = true, features = ["std"] }

[features]
ry = []

[lints]
workspace = true
