[book]
title = "ry(o3) docs"
authors = [
  "jessekrubin",
  # hopefully you!? plz help me build this thingy!
]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
no-section-label = false
git-repository-url = "https://github.com/jessekrubin/ry"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/jessekrubin/ry/edit/main/docs/{path}"
# site-url = "https://jessekrubin.github.io/ry" # gh-pages
site-url = "https://ryo3.dev" # cf
cname = "ryo3.dev"
input-404 = "four-o-four.md"

[preprocessor.py_preprocessor]
command = "uv run ryo3_version.py"
