[package]
name = "ryo3-tokio"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "python + tokio (https://docs.rs/tokio/latest/tokio/)"

[dependencies]
futures.workspace = true
pyo3 = { workspace = true, features = [] }
pyo3-async-runtimes.workspace = true
ryo3-bytes.workspace = true
ryo3-core.workspace = true
ryo3-std = { workspace = true, features = [] }
ryo3-macro-rules = { workspace = true, features = [] }
tokio = { workspace = true, features = [] }
tracing.workspace = true
bytes.workspace = true

[features]
default = []
ry = ["fs", "time"]
fs = ["tokio/fs", "ryo3-std/fs"]
time = ["tokio/time", "ryo3-std/time"]
experimental-async = ["pyo3/experimental-async"]


[lints]
workspace = true
